export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const REMOVE_FETCH_EMPLOYEE = 'REMOVE_FETCH_EMPLOYEE';
export const UPDATE_FETCH_EMPLOYEE = 'UPDATE_FETCH_EMPLOYEE';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const REMOVE_FETCH_USER = 'REMOVE_FETCH_USER';
export const UPDATE_FETCH_USER = 'UPDATE_FETCH_USER';

export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
export const FETCH_ORGANIZATION = 'FETCH_ORGANIZATION';
export const REMOVE_FETCH_ORGANIZATION = 'REMOVE_FETCH_ORGANIZATION';
export const UPDATE_FETCH_ORGANIZATION = 'UPDATE_FETCH_ORGANIZATION';

export const GET_ALL_ATTENDANCE = 'GET_ALL_ATTENDANCE';
export const ADD_TIMEIN_ATTENDANCE = 'ADD_TIMEIN_ATTENDANCE';
export const ADD_TIMEOUT_ATTENDANCE = 'ADD_TIMEOUT_ATTENDANCE';
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE';
export const GET_FILTER_ATTENDANCE = 'GET_FILTER_ATTENDANCE';

export const LOAD_DASHBOARD = 'LOAD_DASHBOARD';

export const API_URL = "https://javee-attendance-backend.herokuapp.com/";
