export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const REMOVE_FETCH_EMPLOYEE = 'REMOVE_FETCH_EMPLOYEE';
export const UPDATE_FETCH_EMPLOYEE = 'UPDATE_FETCH_EMPLOYEE';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const REMOVE_FETCH_USER = 'REMOVE_FETCH_USER';

export const GET_ALL_ATTENDANCE = 'GET_ALL_ATTENDANCE';
export const ADD_ATTENDANCE = 'ADD_ATTENDANCE';

export const API_URL ="http://localhost:8080/";